// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF_efZQFyrI9zKwI_WOqhDW5wNirgYyis',
    appId: '1:47841719219:android:301719bf22001e6f9611c6',
    messagingSenderId: '47841719219',
    projectId: 'elishaswell',
    databaseURL: 'https://elishaswell-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elishaswell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjY7B7YiYEhQHZICMOvKMFAQGm_u3uSs',
    appId: '1:47841719219:ios:89489aed50691a5e9611c6',
    messagingSenderId: '47841719219',
    projectId: 'elishaswell',
    databaseURL: 'https://elishaswell-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'elishaswell.appspot.com',
    androidClientId: '47841719219-fthpaiaiiit4hjcv5475dme144rvpun0.apps.googleusercontent.com',
    iosBundleId: 'com.mystore.store',
  );
}
